#
# Ansible inventory for SHAO cluster
#
#
# Weitian LI
# 2018-01-25
#

# Use the YAML format
# https://docs.ansible.com/ansible/latest/intro_inventory.html

all:
    hosts:
        master:
            # For direct local control
            ansible_ssh_host: localhost
            ansible_ssh_private_key_file: ./ssh/master.key
            # For remotely controlling the master machine.
            #ansible_ssh_host: guotsuan.asuscomm.com
            #ansible_ssh_port: 6666
            #ansible_ssh_private_key_file: ./ssh/master.key

nodes:
    hosts:
        node1:
        node2:
        node3:
        node4:

# vim: set ft=yaml: #
