---
#
# Ansible inventory for SHAO cluster
#
#
# Weitian LI
# 2018-01-25
#

# Use the YAML format
# https://docs.ansible.com/ansible/latest/intro_inventory.html

all:
    hosts:
        localhost:
        node1:
        node2:
        node3:
        node4:
        gpu1:

master:
    hosts:
        localhost:

nodes:
    hosts:
        node1:
        node2:
        node3:
        node4:
        gpu1:

# vim: set ft=yaml: #
